---
- hosts: all
  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/nix-installers.yml
      tags: ['nix', 'never']

    - import_tasks: tasks/nix-installers-fix.yml
      tags: ['nix-temporary']
