---
- name: Download the nix-multi-user.rpm
  get_url:
    url: "https://nix-community.github.io/nix-installers/x86_64/nix-multi-user-2.9.1.rpm"
    dest: /tmp/nix-multi-user.rpm
- name: Get sha256 sum of nix-multi-user.rpm
  stat:
    path: /tmp/nix-multi-user.rpm
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha256sum
- name: Verify sha256sum of nix-multi-user.rpm
  fail:
    msg: "Failure, file is not correct."
  when: sha256sum.stat.checksum != '0d449d0632be8ad74a52fb7640bc39a29ad940f61e2912ae226dba6a950ff455'
- name: Install the nix package manager
  rpm_ostree_pkg:
    name: /tmp/nix-multi-user.rpm
    state: present
- name: Remove the nix-multi-user.rpm file
  file:
    path: /tmp/nix-multi-user.rpm
    state: absent
